timeout: "3600s"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - worker/Dockerfile
      - --build-arg
      - CITYLENS_CORE_GIT_URL=${_CITYLENS_CORE_GIT_URL}
      - --build-arg
      - CITYLENS_SAM2_ASSETS_SIZE=${_CITYLENS_SAM2_ASSETS_SIZE}
      - -t
      - ${_IMAGE}
      - worker
images:
  - ${_IMAGE}
substitutions:
  _CITYLENS_CORE_GIT_URL: ""
  _CITYLENS_SAM2_ASSETS_SIZE: "small"
  _IMAGE: ""
