steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - api/Dockerfile
      - --build-arg
      - CITYLENS_CORE_GIT_URL=${_CITYLENS_CORE_GIT_URL}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _CITYLENS_CORE_GIT_URL: "git+https://github.com/joshvern/citylens-core.git@v0.3.0"
  _IMAGE: ""
